// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvpL4M-NN5wwHH7SOTOaL6QWuntiSVT2E',
    appId: '1:8913413933:web:407f98c9b4cba5533315a4',
    messagingSenderId: '8913413933',
    projectId: 'travel-agency-97d27',
    authDomain: 'travel-agency-97d27.firebaseapp.com',
    storageBucket: 'travel-agency-97d27.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiSCx4zS9WTQoXkUK84eiBlfeiNvngx5Y',
    appId: '1:8913413933:android:fd1f10aede5c80693315a4',
    messagingSenderId: '8913413933',
    projectId: 'travel-agency-97d27',
    storageBucket: 'travel-agency-97d27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKGu2Cn_J6yRg1Du8imwqdogqGQCCDaJA',
    appId: '1:8913413933:ios:76ef07850c6d57b53315a4',
    messagingSenderId: '8913413933',
    projectId: 'travel-agency-97d27',
    storageBucket: 'travel-agency-97d27.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKGu2Cn_J6yRg1Du8imwqdogqGQCCDaJA',
    appId: '1:8913413933:ios:76ef07850c6d57b53315a4',
    messagingSenderId: '8913413933',
    projectId: 'travel-agency-97d27',
    storageBucket: 'travel-agency-97d27.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvpL4M-NN5wwHH7SOTOaL6QWuntiSVT2E',
    appId: '1:8913413933:web:1b3966170e01458d3315a4',
    messagingSenderId: '8913413933',
    projectId: 'travel-agency-97d27',
    authDomain: 'travel-agency-97d27.firebaseapp.com',
    storageBucket: 'travel-agency-97d27.firebasestorage.app',
  );
}
